# Generated by Django 5.0.1 on 2024-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("raw_material", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "production_status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "In Progress"),
                            (3, "Quality Control"),
                            (4, "Ready for Shipping"),
                            (5, "In Transit"),
                            (6, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "production_cost",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("category", models.CharField(blank=True, max_length=250, null=True)),
                ("requirements", models.JSONField()),
                (
                    "raw_materials",
                    models.ManyToManyField(blank=True, to="raw_material.rawmaterial"),
                ),
            ],
        ),
    ]
