# Generated by Django 5.0.1 on 2024-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="requirements",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
