# Generated by Django 5.0.1 on 2024-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_production_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
