# Generated by Django 5.0.1 on 2024-02-01 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_requirements"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="quantity_available",
        ),
    ]
