# Generated by Django 5.0.1 on 2024-02-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_requirements"),
        ("product_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="product_inventory.productinventory",
            ),
        ),
    ]
