# Generated by Django 5.0.1 on 2024-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_rename_quantity_product_quantity_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="production_status",
            field=models.IntegerField(
                choices=[
                    (1, "Created"),
                    (2, "In Progress"),
                    (3, "Quality Control"),
                    (4, "Completed"),
                ],
                default=1,
            ),
        ),
    ]
