# Generated by Django 5.0.1 on 2024-02-07 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_product_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="raw_materials",
        ),
    ]
