# Generated by Django 5.0.1 on 2024-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_product_raw_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="product",
            name="production_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
