# Generated by Django 5.0.1 on 2024-02-02 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_production_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="requirements",
            new_name="raw_material_requirements",
        ),
    ]
