# Generated by Django 5.0.1 on 2024-02-02 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_alter_product_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="inventory",
        ),
    ]
