# Generated by Django 5.0.1 on 2024-02-03 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_rename_requirements_product_raw_material_requirements"),
        ("product", "0012_alter_product_inventory"),
    ]

    operations = []
