# Generated by Django 5.0.1 on 2024-02-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_production_status'),
        ('product', '0012_alter_product_inventory'),
    ]

    operations = [
    ]
