# Generated by Django 5.0.1 on 2024-02-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("inventory", "0004_remove_inventory_inventory_type"),
        ("product_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analytics",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.inventory"
            ),
        ),
        migrations.AlterField(
            model_name="analytics",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="product_inventory.productinventory",
            ),
        ),
    ]
