# Generated by Django 5.0.1 on 2024-02-07 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analytics",
            name="date",
        ),
    ]
