# Generated by Django 5.0.1 on 2024-02-03 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_alter_analytics_inventory_alter_analytics_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analytics",
            old_name="product",
            new_name="product_inventory",
        ),
    ]
