# Generated by Django 5.0.1 on 2024-02-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_remove_analytics_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="analytics",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
