# Generated by Django 5.0.1 on 2024-02-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_inventory", "0002_alter_productinventory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinventory",
            name="description",
            field=models.TextField(
                blank=True,
                default="This inventory holds all your finished products.",
                null=True,
            ),
        ),
    ]
