# Generated by Django 5.0.1 on 2024-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_note", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("delivery_time", models.DurationField(blank=True)),
                ("processing_time", models.DurationField(blank=True)),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "In Progress"),
                            (3, "Quality Control"),
                            (4, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("nr_products", models.IntegerField()),
                ("nr_products_completed", models.IntegerField()),
            ],
        ),
    ]
