# Generated by Django 5.0.1 on 2024-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientorder",
            name="order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
