# Generated by Django 5.0.1 on 2024-02-06 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorder",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
