# Generated by Django 5.0.1 on 2024-02-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0003_alter_clientorder_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorder",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
