# Generated by Django 5.0.1 on 2024-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0003_clientorder_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorder",
            name="client_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
