# Generated by Django 5.0.1 on 2024-02-07 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_remove_analytics_date"),
        ("client_order", "0004_alter_clientorder_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorder",
            name="analytics",
            field=models.ForeignKey(
                blank=True,
                default="Analytics",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_orders",
                to="analytics.analytics",
            ),
        ),
    ]
