# Generated by Django 5.0.1 on 2024-02-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0005_alter_clientorder_delivery_time_and_more"),
        ("product", "0003_rename_quantity_product_quantity_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorder",
            name="products",
            field=models.ManyToManyField(blank=True, to="product.product"),
        ),
    ]
