# Generated by Django 5.0.1 on 2024-02-01 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0006_alter_clientorder_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientorder",
            old_name="order",
            new_name="order_and_quantities",
        ),
    ]
