# Generated by Django 5.0.1 on 2024-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0007_rename_order_clientorder_order_and_quantities"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientorder",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="clientorder",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (1, "Created"),
                    (2, "In Progress"),
                    (3, "Quality Control"),
                    (4, "Ready for Shipping"),
                    (5, "In Transit"),
                    (6, "Completed"),
                ],
                default=1,
            ),
        ),
    ]
