# Generated by Django 5.0.1 on 2024-02-02 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client_order", "0008_clientorder_tracking_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientorder",
            old_name="products",
            new_name="ordered_products",
        ),
    ]
