# Generated by Django 5.0.1 on 2024-02-03 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_alter_analytics_user"),
        ("client_order", "0010_alter_clientorder_nr_products_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientorder",
            name="analytics",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="analytics.analytics",
            ),
        ),
    ]
