# Generated by Django 5.0.1 on 2024-02-03 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_alter_analytics_user"),
        ("client_order", "0011_clientorder_analytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientorder",
            name="analytics",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_orders",
                to="analytics.analytics",
            ),
        ),
    ]
