# Generated by Django 5.0.1 on 2024-01-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
