# Generated by Django 5.0.1 on 2024-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_created_customuser_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="zipcode",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
