# Generated by Django 5.0.1 on 2024-02-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0002_customuser_created_customuser_updated"),
        ("inventory", "0003_inventory_inventory_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="product_inventory",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_inventory",
                to="inventory.inventory",
            ),
        ),
    ]
