# Generated by Django 5.0.1 on 2024-02-02 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0003_customuser_product_inventory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="product_inventory",
        ),
    ]
