# Generated by Django 5.0.1 on 2024-02-03 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("custom_user", "0003_customuser_zipcode"),
        ("custom_user", "0004_remove_customuser_product_inventory"),
    ]

    operations = []
