# Generated by Django 5.0.1 on 2024-02-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_inventory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="inventory_type",
            field=models.CharField(
                choices=[("raw_materials", "Raw Materials"), ("products", "Products")],
                default="raw_materials",
                max_length=50,
            ),
        ),
    ]
