# Generated by Django 5.0.1 on 2024-02-02 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_inventory_inventory_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventory",
            name="inventory_type",
        ),
    ]
