# Generated by Django 5.0.1 on 2024-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_inventory_inventory_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="description",
            field=models.TextField(
                blank=True, default="This inventory holds all raw materials.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="name",
            field=models.CharField(default="raw_material_inventory", max_length=250),
        ),
    ]
