# Generated by Django 5.0.1 on 2024-01-30 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("raw_material", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rawmaterial",
            old_name="title",
            new_name="name",
        ),
    ]
