# Generated by Django 5.0.1 on 2024-02-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_material", "0002_alter_rawmaterial_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
