# Generated by Django 5.0.1 on 2024-02-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_material", "0003_rename_quantity_rawmaterial_quantity_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterial",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
