# Generated by Django 5.0.1 on 2024-02-04 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_inventory_description_alter_inventory_name"),
        ("raw_material", "0004_rawmaterial_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.inventory",
            ),
        ),
    ]
