# Generated by Django 5.0.1 on 2024-02-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_material", "0005_alter_rawmaterial_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterial",
            name="max_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rawmaterial",
            name="quantity_available",
            field=models.IntegerField(default=0),
        ),
    ]
