# Generated by Django 5.0.1 on 2024-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_material_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterialorder",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawmaterialorder",
            name="order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
