# Generated by Django 5.0.1 on 2024-02-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_material", "0003_rename_quantity_rawmaterial_quantity_available"),
        (
            "raw_material_order",
            "0003_rename_raw_material_rawmaterialorder_raw_materials_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterialorder",
            name="raw_materials",
            field=models.ManyToManyField(blank=True, to="raw_material.rawmaterial"),
        ),
    ]
