# Generated by Django 5.0.1 on 2024-02-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_material_order", "0004_alter_rawmaterialorder_raw_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterialorder",
            name="quantity",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
