# Generated by Django 5.0.1 on 2024-02-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_alter_analytics_user"),
        ("raw_material_order", "0006_rawmaterialorder_analytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawmaterialorder",
            name="analytics",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_material_orders",
                to="analytics.analytics",
            ),
        ),
    ]
